name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  destination-github-username:
    description: Name of the destination username/organization
    required: true
  destination-repository-name:
    description: Destination repository
    required: true
  user-email:
    description: Email for the git commit
    required: true
  user-name:
    description: >-
      [Optional] Name for the git commit. Defaults to the destination
      username/organization name
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.destination-github-username }}'
    - '${{ inputs.destination-respository-name }}'
    - '${{ inputs.user-email }}'
    - '${{ inputs.user-name }}'
branding:
  icon: 'git-commit'
  color: 'green'
