name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  user-email:
    description: Email for the git commit
    required: true
  user-name:
    description: >-
      User name for the git commit. Defaults to the destination
      username/organization name
    required: true
    default: ''
  github-token:
    description: 'Token needed to pass into the action'
    default: ''
    required: true
        
runs:
  using: docker
  image: Dockerfile
  args:
    - '${{ inputs.user-email }}'
    - '${{ inputs.user-name }}'
    - '${{ inputs.github-token }}'
branding:
  icon: git-commit
  color: green
