name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'green'
